// // =============== MOCK DATA ===============
// export const PRODUCTS = [
//   {
//     id: 1,
//     name: 'iPhone 15 Pro Max 256GB',
//     brand: 'Apple',
//     price: 27990000,
//     oldPrice: 30990000,
//     ram: 8,
//     rom: 256,
//     color: 'Titan Xanh',
//     condition: 'new',
//     badge: 'Sale',
//     rating: 4.9,
//     reviews: 132,
//     img: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-max-storage-select-202309-6-7inch-bluetitanium?wid=600&hei=600&fmt=jpeg&qlt=90&.v=1693010550074',
//     gallery: [],
//     description: 'Chip A17 Pro mới, thiết kế Titanium siêu nhẹ, camera 48MP, USB-C.',
//     variants: {
//       colors: ['Titan Xanh', 'Titan Tự Nhiên', 'Titan Trắng'],
//       roms: [256, 512],
//     },
//     tags: ['iphone', 'flagship'],
//     isHotDeal: true,
//   },
//   {
//     id: 2,
//     name: 'Samsung Galaxy S24 Ultra 12GB 256GB',
//     brand: 'Samsung',
//     price: 24990000,
//     oldPrice: 26990000,
//     ram: 12,
//     rom: 256,
//     color: 'Xám Titan',
//     condition: 'new',
//     badge: 'New',
//     rating: 4.8,
//     reviews: 98,
//     img: 'https://images.samsung.com/is/image/samsung/p6pim/vn/2401/gallery/vn-galaxy-s24-ultra-s928-sm-s928bztqxxv-539939309?$650_519_PNG$',
//     gallery: [],
//     description: 'Màn hình 120Hz, camera zoom 100x, S-Pen, hiệu năng mạnh mẽ.',
//     variants: {
//       colors: ['Xám Titan', 'Đen', 'Tím'],
//       roms: [256, 512],
//     },
//     tags: ['android', 'flagship'],
//     isHotDeal: true,
//   },
//   {
//     id: 3,
//     name: 'Xiaomi Redmi Note 13 Pro 8GB 256GB',
//     brand: 'Xiaomi',
//     price: 7990000,
//     oldPrice: 8990000,
//     ram: 8,
//     rom: 256,
//     color: 'Xanh',
//     condition: 'new',
//     badge: 'Best value',
//     rating: 4.7,
//     reviews: 210,
//     img: 'https://i01.appmifile.com/webfile/globalimg/products/pc/redmi-note-13-pro/blue.png',
//     gallery: [],
//     description: 'Pin trâu, sạc nhanh, camera 200MP, màn AMOLED 120Hz.',
//     variants: {
//       colors: ['Xanh', 'Đen'],
//       roms: [256],
//     },
//     tags: ['budget', 'gaming'],
//     isHotDeal: true,
//   },
//   {
//     id: 4,
//     name: 'iPhone 13 128GB (Like New 99%)',
//     brand: 'Apple',
//     price: 10990000,
//     oldPrice: 12990000,
//     ram: 4,
//     rom: 128,
//     color: 'Trắng',
//     condition: 'used',
//     badge: 'Like new',
//     rating: 4.8,
//     reviews: 320,
//     img: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-select-2021?wid=600&hei=600&fmt=jpeg&qlt=90&.v=1645572316342',
//     gallery: [],
//     description: 'Máy dùng lướt, ngoại hình đẹp, pin tốt, bảo hành 6 tháng.',
//     variants: {
//       colors: ['Trắng', 'Đen'],
//       roms: [128],
//     },
//     tags: ['iphone', 'budget'],
//     isHotDeal: false,
//   },
//   {
//     id: 5,
//     name: 'POCO X6 Pro 12GB 256GB',
//     brand: 'Xiaomi',
//     price: 8990000,
//     oldPrice: 9990000,
//     ram: 12,
//     rom: 256,
//     color: 'Vàng',
//     condition: 'new',
//     badge: 'Gaming',
//     rating: 4.6,
//     reviews: 145,
//     img: 'https://i01.appmifile.com/webfile/globalimg/products/pc/poco-x6-pro/yellow.png',
//     gallery: [],
//     description: 'Hiệu năng mạnh, tối ưu chơi game, tản nhiệt tốt, sạc nhanh.',
//     variants: {
//       colors: ['Vàng', 'Đen'],
//       roms: [256],
//     },
//     tags: ['gaming', 'android'],
//     isHotDeal: false,
//   },
//   {
//     id: 6,
//     name: 'Oppo Reno 11 5G 8GB 256GB',
//     brand: 'Oppo',
//     price: 10490000,
//     oldPrice: 11490000,
//     ram: 8,
//     rom: 256,
//     color: 'Xanh ngọc',
//     condition: 'new',
//     badge: 'New',
//     rating: 4.5,
//     reviews: 87,
//     img: 'https://image.oppo.com/content/dam/oppo/common/mkt/v2-2/reno11-5g-en/nav/reno11-green-600x600.png',
//     gallery: [],
//     description: 'Thiết kế mỏng nhẹ, camera chân dung đẹp, sạc nhanh.',
//     variants: {
//       colors: ['Xanh ngọc', 'Trắng'],
//       roms: [256],
//     },
//     tags: ['camera'],
//     isHotDeal: false,
//   },
// ];

// export const COUPONS = [
//   { code: 'WELCOME10', type: 'percent', value: 10 },
//   { code: 'BLACKFRIDAY', type: 'percent', value: 20 },
// ];

// export const DEFAULT_USERS = [
//   { id: 1, name: 'Admin', email: 'admin@shop.vn', password: '123456', role: 'admin' },
//   { id: 2, name: 'Khách demo', email: 'user@shop.vn', password: '123456', role: 'customer' },
// ];

// export const STORAGE_KEYS = {
//   CART: 'ps_cart',
//   ORDERS: 'ps_orders',
//   USER: 'ps_current_user',
//   USERS: 'ps_users',
// };
